// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCHLkbjLn-fIidgTCY0fmbkBvZzRQS8vY',
    appId: '1:916966489485:web:697e671e94d7367beed1c4',
    messagingSenderId: '916966489485',
    projectId: 'book-e60d3',
    authDomain: 'book-e60d3.firebaseapp.com',
    storageBucket: 'book-e60d3.firebasestorage.app',
    measurementId: 'G-WS6CEZ7V12',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB34SXjTz1Xwo0yLiqXYDlmrsTBkoGC-hA',
    appId: '1:916966489485:android:cf239670c80c1763eed1c4',
    messagingSenderId: '916966489485',
    projectId: 'book-e60d3',
    storageBucket: 'book-e60d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmYy9tdMbsPBTFEFKQWrFc33KEzPmY7Qw',
    appId: '1:916966489485:ios:f0798acd5affb95feed1c4',
    messagingSenderId: '916966489485',
    projectId: 'book-e60d3',
    storageBucket: 'book-e60d3.firebasestorage.app',
    iosBundleId: 'com.example.lkTravelmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmYy9tdMbsPBTFEFKQWrFc33KEzPmY7Qw',
    appId: '1:916966489485:ios:f0798acd5affb95feed1c4',
    messagingSenderId: '916966489485',
    projectId: 'book-e60d3',
    storageBucket: 'book-e60d3.firebasestorage.app',
    iosBundleId: 'com.example.lkTravelmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCHLkbjLn-fIidgTCY0fmbkBvZzRQS8vY',
    appId: '1:916966489485:web:697e671e94d7367beed1c4',
    messagingSenderId: '916966489485',
    projectId: 'book-e60d3',
    authDomain: 'book-e60d3.firebaseapp.com',
    storageBucket: 'book-e60d3.firebasestorage.app',
    measurementId: 'G-WS6CEZ7V12',
  );
}
