// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsxduEGriI2eM724LgGuSnRqZehUZelVE',
    appId: '1:479173819539:web:293426aa0bbb79d815a166',
    messagingSenderId: '479173819539',
    projectId: 'lk-travelmate',
    authDomain: 'lk-travelmate.firebaseapp.com',
    storageBucket: 'lk-travelmate.firebasestorage.app',
    measurementId: 'G-4LKTK2TDEY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsmSDbsnb2o41yd-4VfB47d_iAdQsRTbQ',
    appId: '1:479173819539:android:5291a1ebd21b7e7015a166',
    messagingSenderId: '479173819539',
    projectId: 'lk-travelmate',
    storageBucket: 'lk-travelmate.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsWMzKBfCaN7t06aFN1ehOUvoesOLG48E',
    appId: '1:479173819539:ios:d97c3a0a873085e515a166',
    messagingSenderId: '479173819539',
    projectId: 'lk-travelmate',
    storageBucket: 'lk-travelmate.firebasestorage.app',
    iosBundleId: 'com.example.lkTravelmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsWMzKBfCaN7t06aFN1ehOUvoesOLG48E',
    appId: '1:479173819539:ios:d97c3a0a873085e515a166',
    messagingSenderId: '479173819539',
    projectId: 'lk-travelmate',
    storageBucket: 'lk-travelmate.firebasestorage.app',
    iosBundleId: 'com.example.lkTravelmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsxduEGriI2eM724LgGuSnRqZehUZelVE',
    appId: '1:479173819539:web:650786c6dd91739e15a166',
    messagingSenderId: '479173819539',
    projectId: 'lk-travelmate',
    authDomain: 'lk-travelmate.firebaseapp.com',
    storageBucket: 'lk-travelmate.firebasestorage.app',
    measurementId: 'G-PNJJD0DK9M',
  );

}